[package]
name = "attestation-gateway"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/worldcoin/attestation-gateway"
description = "Protects app integrity."
license-file = "LICENSE"
keywords = ["integrity", "attestation", "PlayIntegrity", "DeviceCheck"]
categories = ["web-programming"]


[dependencies]
aide = { version = "0.13.4", features = ["axum", "macros", "scalar"] }
anyhow = "1.0.86"
aws-config = "1.5.4"
aws-sdk-dynamodb = "1.39.1"
aws-sdk-kms = "1.37.0"
axum = "0.7.5"
axum-jsonschema = { version = "0.8.0", features = ["aide"] }
base64 = "0.22.1"
chrono = "0.4.38"
ciborium = "0.2.2"
der-parser = "9.0.0"
dotenvy = "0.15.7"
eyre = "0.6.12"
hex = "0.4.3"
josekit = "0.8.6"
metrics = "0.23.0"
metrics-exporter-statsd = "0.8.0"
openssl = "0.10.66"
redis = { version = "0.25.4", features = ["tokio-comp", "connection-manager", "tokio-native-tls-comp"] }
regex = "1.10.6"
schemars = "0.8.21"
serde = { version = "1.0.204", features = ["derive"] }
serde_bytes = "0.11.15"
serde_json = "1.0.122"
tokio = { version = "1.39.2", features = ["full"] }
tower-http = { version = "0.5.2", features = ["trace", "timeout"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt","json"
] }
x509-parser = "0.16.0"


[build-dependencies]
chrono = "0.4.38"

[dev-dependencies]
http-body-util = "0.1.2"
hyper = "1.4.1"
mime = "0.3.17"
serial_test = "3.1.1"
tower = "0.4.13"
tracing-test = { version = "0.2.5", features = ["no-env-filter"] }
